# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
use_frameworks!
use_modular_headers!

target 'OCRingsSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxRelay', '~> 6.8.0'
  pod 'RxSwift', '~> 6.8.0'
  
  pod 'RingsSDK', :path => 'Frameworks/RingsSDK'
  pod 'ApolloOTA', :path => 'Frameworks/ApolloSDK'

end

# 添加 post_install 钩子
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
